services:
  metrika:
    build:
      context: ./nextjs-app
      dockerfile: Dockerfile
    container_name: metrika
    restart: unless-stopped
    env_file:
      - ./nextjs-app/.env
    environment:
      - NODE_ENV=production
      - TZ=Europe/Moscow
    volumes:
      - ./nextjs-app/data.db:/app/data.db
      - ./nextjs-app/metadata.db:/app/metadata.db
    networks:
      - wg-pihole
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metrika.rule=Host(`app.marais.ru`)"
      - "traefik.http.routers.metrika.entrypoints=web"
      - "traefik.http.routers.metrika.priority=100"
      - "traefik.http.services.metrika.loadbalancer.server.port=3000"

networks:
  wg-pihole:
    external: true
